apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
    component: web
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      app: website
      component: web
  template:
    metadata:
      labels:
        app: website
        component: web
    spec:
      containers:
      - name: website
        image: enyediaz/project-7:latest
        env:
        - name: MONGODB_URI
          value: mongodb://mongodb:27017
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi